/**
 * PDF Generator using jsPDF
 * Creates branded PDF documents with payment schedules
 */

/**
 * Generates and downloads a PDF with payment schedules
 * @param {Array} schedules - Array of payment schedule objects
 * @param {number} propertyPrice - The property price
 */
function generatePDF(schedules, propertyPrice) {
  if (!schedules || schedules.length === 0) {
    console.error('No schedules provided for PDF generation');
    return;
  }

  // Check if jsPDF is loaded
  if (typeof window.jspdf === 'undefined') {
    console.error('jsPDF library not loaded');
    alert('PDF library not loaded. Please refresh the page and try again.');
    return;
  }

  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  // Add Header
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Payment Plan Comparison', pageWidth / 2, 20, { align: 'center' });

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Real Estate Payment Calculator', pageWidth / 2, 30, { align: 'center' });

  yPosition = 50;

  // Add Property Details
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Property Details', 14, yPosition);

  yPosition += 8;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Property Price: ${formatCurrency(propertyPrice)}`, 14, yPosition);

  yPosition += 6;
  const today = new Date().toLocaleDateString('en-IN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  doc.text(`Generated on: ${today}`, 14, yPosition);

  yPosition += 12;

  // Add each payment schedule
  schedules.forEach((schedule, index) => {
    // Check if we need a new page
    if (yPosition > pageHeight - 80) {
      doc.addPage();
      yPosition = 20;
    }

    // Plan Name
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(37, 99, 235);
    doc.text(`${index + 1}. ${schedule.planName}`, 14, yPosition);

    yPosition += 8;

    // Create table data
    const tableData = schedule.installments.map(inst => [
      inst.installmentNumber.toString(),
      inst.stage,
      `${inst.percentage}%`,
      formatCurrency(inst.amount)
    ]);

    // Add total row
    tableData.push([
      '',
      'TOTAL',
      '100%',
      formatCurrency(schedule.totalAmount)
    ]);

    // Generate table using autoTable
    doc.autoTable({
      startY: yPosition,
      head: [['#', 'Payment Stage', 'Percentage', 'Amount (₹)']],
      body: tableData,
      theme: 'striped',
      headStyles: {
        fillColor: [37, 99, 235],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 10
      },
      bodyStyles: {
        fontSize: 9
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252]
      },
      columnStyles: {
        0: { cellWidth: 15, halign: 'center' },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 30, halign: 'center' },
        3: { cellWidth: 45, halign: 'right' }
      },
      footStyles: {
        fillColor: [241, 245, 249],
        textColor: [0, 0, 0],
        fontStyle: 'bold'
      },
      didParseCell: function(data) {
        // Make total row bold
        if (data.row.index === tableData.length - 1) {
          data.cell.styles.fontStyle = 'bold';
          data.cell.styles.fillColor = [241, 245, 249];
        }
      },
      margin: { left: 14, right: 14 }
    });

    yPosition = doc.lastAutoTable.finalY + 15;
  });

  // Add Disclaimer
  if (yPosition > pageHeight - 40) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(100, 116, 139);
  const disclaimer = 'Disclaimer: This is an estimate based on standard payment plan structures. Actual payment schedules may vary by developer and project. Please consult with the sales team for exact payment terms.';

  const disclaimerLines = doc.splitTextToSize(disclaimer, pageWidth - 28);
  doc.text(disclaimerLines, 14, yPosition);

  // Add Footer
  const footerY = pageHeight - 15;
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by Real Estate Payment Calculator', pageWidth / 2, footerY, { align: 'center' });

  doc.setFontSize(7);
  doc.text(`© ${new Date().getFullYear()} All rights reserved`, pageWidth / 2, footerY + 4, { align: 'center' });

  // Generate filename
  const filename = `Payment_Plan_Comparison_${formatDateForFilename()}.pdf`;

  // Save the PDF
  doc.save(filename);
}

/**
 * Formats date for filename (YYYY-MM-DD)
 * @returns {string} - Formatted date string
 */
function formatDateForFilename() {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

// Export for use in browser and Node.js
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    generatePDF,
    formatDateForFilename
  };
}
